version: '2'
services:
    #   starwars-app:
    #       image: starwars-app:latest
    #       container_name: starwars-app
    #       build:
    #           context: .
    #           dockerfile: Dockerfile
    #       depends_on:
    #           - starwars-db
    #       environment:
    #           - SPRING_DATASOURCE_URL=jdbc:mysql://starwars-db:5432/starwars?allowPublicKeyRetrieval=true&useSSL=false
    #           - SPRING_DATASOURCE_USERNAME=user1
    #           - SPRING_DATASOURCE_PASSWORD=password1
    #           - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    #           - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    #           - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    #           - SPRING_JPA_GENERATE_DLL=true
    #       ports:
    #           - 8887:8080
    #       networks:
    #           - spring-cloud-network
    starwars-db:
        image: mysql
        container_name: starwars-db
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword1
            - MYSQL_DATABASE=starwars
            - MYSQL_USER=user1
            - MYSQL_PASSWORD=password1
        ports:
            - 5432:3306
        healthcheck:
            test: "/usr/bin/mysql --user=user1 --password=password1 --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
#   networks:
#       spring-cloud-network:
#           driver: bridge